In [1]:
import pandas as pd
from scipy.stats import gmean

In [2]:
base = pd.read_csv('../dataset/dados historicos bitcoin.csv')

In [3]:
pd.set_option('display.max_rows', 10)

In [ ]:
base

In [ ]:
base.dtypes

## 1. Limpeza e formatação dos dados

### Limpeza de strings e modificando valores

In [4]:
base['Var%'] = base['Var%'].str.replace(',', '.')
base['Var%'] = base['Var%'].str.replace('%','')
base['Último'] = base['Último'].str.replace('.', '')
base['Último'] = base['Último'].str.replace(',', '.')
base['Abertura'] = base['Abertura'].str.replace('.', '')
base['Abertura'] = base['Abertura'].str.replace(',', '.')
base['Máxima'] = base['Máxima'].str.replace('.','')
base['Máxima'] = base['Máxima'].str.replace(',', '.')

In [ ]:
base['Abertura']

### Convertendo tipos

In [5]:
base['Data'] = pd.to_datetime(base['Data'], format='%d.%m.%Y')

base['Último'] = pd.to_numeric(base['Último'])
base['Abertura'] = pd.to_numeric(base['Abertura'])

base['Var%'] = base['Var%'].astype(float)

In [ ]:
base.dtypes

### Criação de colunas

In [6]:
base['Mês'] = base['Data'].dt.month
base['Ano'] = base['Data'].dt.year

In [7]:
base[base['Mês'] == 8]

,Data,Último,Abertura,Máxima,Mínima,Vol.,Var%,Mês,Ano
5,2025-08-01,108226.8,115766.7,124436.8,"107.433,4","1,58M",-6.51,8,2025
17,2024-08-01,58978.6,64625.7,65587.9,"49.486,9","2,56M",-8.74,8,2024
29,2023-08-01,25937.3,29232.3,30168.6,"25.481,9","1,34M",-11.27,8,2023
41,2022-08-01,20043.9,23303.4,25205.7,"19.542,9","6,55M",-13.99,8,2022
53,2021-08-01,47130.4,41510.0,50498.8,"37.365,4","2,14M",13.42,8,2021
...,...,...,...,...,...,...,...,...,...
137,2014-08-01,481.8,589.5,608.2,"450,0","126,17K",-18.28,8,2014
149,2013-08-01,141.0,106.2,148.7,"101,0","604,91K",32.76,8,2013
161,2012-08-01,10.2,9.4,15.4,"7,6","2,45M",8.66,8,2012
173,2011-08-01,8.2,13.4,13.6,"5,7","1,22M",-38.58,8,2011
185,2010-08-01,0.1,0.1,0.1,"0,0","221,74K",0.00,8,2010

In [ ]:
base[base['Mês'] == 2]

## 2. Análise exploratória

In [7]:
base_sem2026 = base[base['Ano'] != 2026]

base_filter = base_sem2026[['Data','Abertura', 'Último', 'Vol.', 'Var%', 'Mês', 'Ano']]

### Dataframe apenas com valores negativos

In [8]:
base_negativos = base_filter[base_filter['Var%'] <= 0]
tabela_final_ne = base_negativos.sort_values(['Mês', 'Ano'])

### Dataframe apenas com valores positivos

In [9]:
base_positivos = base_filter[base_filter['Var%'] > 0]
tabela_final_po = base_positivos.sort_values(['Mês', 'Ano'])

In [19]:
tabela_final_po

          Data  Abertura   Último     Vol.   Var%  Mês   Ano
180 2011-01-01       0.3      0.5  377,75K  73.33    1  2011
168 2012-01-01       4.7      5.5    3,21M  16.10    1  2012
156 2013-01-01      13.5     20.4    1,46M  51.07    1  2013
144 2014-01-01     805.9    938.8  306,25K  16.49    1  2014
108 2017-01-01     963.4    965.5    2,21M   0.22    1  2017
..         ...       ...      ...      ...    ...  ...   ...
121 2015-12-01     378.0    430.0    3,20M  13.75   12  2015
109 2016-12-01     742.5    963.4    1,27M  29.75   12  2016
97  2017-12-01    9947.1  13850.4    5,12M  39.25   12  2017
61  2020-12-01   19697.8  28949.4    3,85M  46.97   12  2020
25  2023-12-01   37712.9  42272.5    1,63M  12.09   12  2023

[105 rows x 7 columns]

### Criação da lista de meses com mais variações negativas

In [10]:
meses_negativos_7_ocorrencias = list()

print('MESES NEGATIVOS!')

for mes_n, tabela_n in tabela_final_ne.groupby('Mês'):
    if tabela_n['Var%'].count() >= 7:
        print(f"\n Foram encontrados {tabela_n['Var%'].count()} válores negativos no mês {mes_n} entre 2010 e 2025") # é apenas um log
        meses_negativos_7_ocorrencias.append(mes_n)

MESES NEGATIVOS!

 Foram encontrados 9 válores negativos no mês 3 entre 2010 e 2025

 Foram encontrados 11 válores negativos no mês 8 entre 2010 e 2025

 Foram encontrados 9 válores negativos no mês 9 entre 2010 e 2025

 Foram encontrados 7 válores negativos no mês 11 entre 2010 e 2025

 Foram encontrados 8 válores negativos no mês 12 entre 2010 e 2025

In [13]:
meses_negativos_7_ocorrencias

[3, 8, 9, 11, 12]

### Criação da lista de meses com mais variações positivas

In [11]:
meses_positivos_7_ocorrencias = list()

print("\n MESES POSITIVOS!")

for mes_p, tabela_p in tabela_final_po.groupby('Mês'):
    if tabela_p['Var%'].count() > 7:
        meses_positivos_7_ocorrencias.append(mes_p)
        print(f"\n Foram encontrados {tabela_p['Var%'].count()} válores positivos no mês {mes_p} entre 2010 e 2025") # é apenas um log

 MESES POSITIVOS!

 Foram encontrados 10 válores positivos no mês 1 entre 2010 e 2025

 Foram encontrados 11 válores positivos no mês 2 entre 2010 e 2025

 Foram encontrados 10 válores positivos no mês 4 entre 2010 e 2025

 Foram encontrados 9 válores positivos no mês 5 entre 2010 e 2025

 Foram encontrados 9 válores positivos no mês 6 entre 2010 e 2025

 Foram encontrados 10 válores positivos no mês 7 entre 2010 e 2025

 Foram encontrados 11 válores positivos no mês 10 entre 2010 e 2025

 Foram encontrados 9 válores positivos no mês 11 entre 2010 e 2025

 Foram encontrados 8 válores positivos no mês 12 entre 2010 e 2025

In [14]:
meses_positivos_7_ocorrencias

[]

### Cálculo de média negativos

In [12]:
base_filter[base_filter['Mês'].isin(meses_negativos_7_ocorrencias)].groupby('Mês')['Var%'].mean()

Mês
3     10.1520
8     -1.0150
9     -3.3350
11    35.0675
12    10.1750
Name: Var%, dtype: float64

### Cálculo de média positivos

In [13]:
# base_filter[base_filter['Mês'].isin(meses_positivos_7_ocorrencias)].groupby('Mês')['Var%'].mean()
clean_data = base_filter['Var%'].dropna()

gmean(clean_data /100 + 1) -1

# OBS: todo número negativo é tratado como "nan", temos que tratar isso de alguma forma!

0.07899552036980628

In [ ]:
"""
janeiro, junho e julho são meses com média de desempenho pior do que março e dezembro mesmo que março e dezembro tenha uma quantidade
de fechamentos negativos maior, por quê?
"""

In [ ]:
base.sort_values(by='Data')

In [15]:
base_filter[base_filter['Mês'] == 8]

          Data  Abertura    Último     Vol.   Var%  Mês   Ano
5   2025-08-01  115766.7  108226.8    1,58M  -6.51    8  2025
17  2024-08-01   64625.7   58978.6    2,56M  -8.74    8  2024
29  2023-08-01   29232.3   25937.3    1,34M -11.27    8  2023
41  2022-08-01   23303.4   20043.9    6,55M -13.99    8  2022
53  2021-08-01   41510.0   47130.4    2,14M  13.42    8  2021
..         ...       ...       ...      ...    ...  ...   ...
137 2014-08-01     589.5     481.8  126,17K -18.28    8  2014
149 2013-08-01     106.2     141.0  604,91K  32.76    8  2013
161 2012-08-01       9.4      10.2    2,45M   8.66    8  2012
173 2011-08-01      13.4       8.2    1,22M -38.58    8  2011
185 2010-08-01       0.1       0.1  221,74K   0.00    8  2010

[16 rows x 7 columns]

## Quantas vezes cada mês com piores desempenhos foram positivos?

In [ ]:
for mes_posi, tabela_p in base_positivos.groupby('Mês'):
    for valor in meses_negativos_7_ocorrencias:
        if mes_posi == valor:
            print("\n"f" Foram contabilizados {tabela_p['Var%'].count()} valores positivos no mês {mes_p}", "\n")

In [ ]:
for m, tabela_posi in base_positivos.groupby('Mês'):
    print(f" Foram contabilizados {tabela_posi['Var%'].count()} valores positivos no mês {m}", "\n")

## Quão grande é a queda em agosto e setembro comparado a queda em outros meses? devemos nos preocuparmos?

In [ ]:
A queda em agosto em média não costuma ser grande comparado a outros meses com mal desempenho históricamente,
tendo uma variação de apenas −0,66% a −2,26%.
A menos que seja ano de bearmarket, não há motivos para se preocupar com a queda em agosto visto que costuma 
ser uma correção saúdavel. O histórico mostra que em bearmakets, o preço pode alcançar patamares de até -38% de 
queda.

In [ ]:
tabela_media = tabela_final.copy()

In [ ]:
tabela_agosto = tabela_media[tabela_media['Mês'].isin(lista_meses)]

In [ ]:

for linha in meses_negativos_7_ocorrencias:
    tabela_para_media = tabela_agosto[tabela_agosto['Mês'] == linha]
    print(f"Mês {linha}: {tabela_para_media['Var%'].mean()}\n")
    print()

In [ ]:
base_filter_copia = base_filter.copy()
valores_negativos = base_negativos.copy()

In [ ]:
print(f"São {base_positivos['Var%'].count()} valores positivos na coluna 'Var%'")
print(f"São {base_negativos['Var%'].count()} valores negativos na coluna 'Var%'")

In [ ]:
base.to_excel("Dataset Bitcoin Formatado.xlsx")